# Site
name: "Dominant In Chastity Blog"
description: "TODO"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "TODO@TODO.com"
mailchimp-list: "TODO"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  DominantInChastity:
    name: Dominant In Chastity
    site: https://dic.loctober.art
    avatar: /assets/images/dic_avatar.png
    bio: "Hi, I am DIC, author of this blog. TODO"
    email: TODO@TODO.com
    twitter: https://twitter.com/TODO

defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dic
      avatar: /assets/images/dic_avatar.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
